# Generated by Django 4.2.2 on 2024-07-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_course_owner_lessons_owner'),
        ('payments', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='course',
        ),
        migrations.AddField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='оплаченный курс'),
        ),
    ]
