# Generated by Django 4.2.2 on 2024-07-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_subscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='id сессии'),
        ),
    ]
