# Generated by Django 4.2.2 on 2024-07-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payments_options_remove_payments_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
