# Generated by Django 4.2.2 on 2024-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lessons_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='materials/materials_preview', verbose_name='Изображение'),
        ),
    ]
