# Generated by Django 4.2.2 on 2024-07-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_lessons_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='preview',
        ),
    ]
