# Generated by Django 4.2.2 on 2024-07-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_lessons_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='materials/materials_preview', verbose_name='Изображение'),
        ),
    ]
