# Generated by Django 4.2.2 on 2024-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_lessons_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='materials/materials_preview', verbose_name='Изображение'),
        ),
    ]
