# Generated by Django 4.2.2 on 2024-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_course_owner_lessons_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена курса'),
        ),
    ]
