# Generated by Django 4.2.2 on 2024-07-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_lessons_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена курса'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена урока'),
        ),
    ]
