# Generated by Django 4.2.2 on 2024-07-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_course_update_date_lessons_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
