# Generated by Django 4.2.2 on 2024-07-28 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_alter_course_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 29, 0, 14, 43, 874726), null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 29, 0, 14, 43, 874726), null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
